name: publish Ardalis.CleanArchitecture Template to nuget
on:
  workflow_dispatch:
    branches:
      - main # Your default release branch
    paths:
      - 'LhdCleanArchitecture.nuspec'
jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - name: Package the template
        run: nuget pack LhdCleanArchitecture.nuspec -NoDefaultExcludes
        
      - name: Publish to nuget.org
        run: nuget push LHD.CleanArchitecture.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
